# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843363838fd5fb1548e11be52af309b57363627a4bc2ce6741aae22fa39515ce2880edbaa1774ba25b6479a319f09cad077a6964c34471ff16237e2943441b99

test:
  secret_key_base: b2a9da1c9a1b28cc29a6c71a2589bfbbc35c4298b1e025e5b0a33b407eb3fd880ed67246192ef3b34eba7dc0928a916b593e9330c9e99d575be20049c377eebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
